### ISSUE TITLE
Repo/gem name too general

### ISSUE THREAD

**Issue by mtho11** [cfcosta/generic_view_mapper#1]
For me, **match_view** is a little too general a name for this gem, as it could apply to anything and doesn't describe it's purpose. Something more specific would probably fit better as a MiQ gem. 

Perhaps we should poll others?

**Comment by cfcosta** [comment]
I agree with the name change, any suggestions? I'll keep the first release on hold until we find a better name.

**Comment by mtho11** [comment]
@abonas any suggestions for gem name here?

**Comment by mtho11** [comment]
Since this will be generic and not middleware specific. How about **manageiq_generic_view_mapper** -- just to start throwing some ideas out there.

**Comment by cfcosta** [comment]
I like `generic_view_mapper`, because it is not tied to ManageIQ in any way (at least on implementation).

**Comment by abonas** [comment]
if it is bound to manageiq, it is better to reside in manageiq org.
if it is not bound to manageiq then it should not contain the name manageiq :)
but I would definitely ask the larger team @karelhala @tumido @xeviknal @israel-hdez

**Comment by karelhala** [comment]
Drop the MiQ name and let's just use `generic_view_mapper`. Pretty straight forward and easy to remeber.

**Comment by israel-hdez** [comment]
I'm ok with the chosen name :)

**Comment by cfcosta** [comment]
Done!
